export const ItemDatabase = {
  "plume": {
    type: "Passif",
    name: "Plume",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { speed: 0.1 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "ingenieur": {
    type: "Passif",
    name: "Ingénieur",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damage: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "marteau": {
    type: "Passif",
    name: "Marteau",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damage: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "recharge": {
    type: "Passif",
    name: "Recharge",
    sprite: "",
    bonus: "Cadence de tire",
    modifiers: { fireRate: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "pierre": {
    type: "Passif",
    name: "Pierre",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { damage: 0.5, speed: -0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "feuille": {
    type: "Passif",
    name: "Feuille",
    sprite: "",
    bonus: "Dégâts",
    modifiers: { luck: 0.5, damage: -0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "ciseaux": {
    type: "Passif",
    name: "Ciseaux",
    sprite: "",
    bonus: "Chance",
    modifiers: { speed: 0.5, luck: -0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "cable_d_acier": {
    type: "Passif",
    name: "Câble d'Acier",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damage: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "moteur_turbo": {
    type: "Passif",
    name: "Moteur Turbo",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { speed: 0.15 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "puce_aleatoire": {
    type: "Passif",
    name: "Puce Aléatoire",
    sprite: "",
    bonus: "Chance",
    modifiers: { luck: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "watercooling": {
    type: "Passif",
    name: "Watercooling",
    sprite: "",
    bonus: "Cooldown",
    modifiers: { cooldownReduction: 0.05 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1,
    extraInfo: "Réduction des cooldown (activable et items à cd)"
  },
  "cd_douteux": {
    type: "Passif",
    name: "CD Douteux",
    sprite: "",
    bonus: "Dégâts // Vitesse ",
    modifiers: { damage: 0.5, speed: -0.3 },
    pool: "chest",
    procChance: 0.5,
    target: "self",
    slot: "none",
    rarity: 1,
    extraInfo: "Item de gambling, soit buff, soit debuff"
  },
  "chargeur_rapide": {
    type: "Passif",
    name: "Chargeur rapide",
    sprite: "",
    bonus: "cadence de tire",
    modifiers: { fireRate: 0.2 },
    pool: "chest",
    duration: Infinity,
    target: "self",
    slot: "none",
    rarity: 1
  },
  "bottes_de_cowboy": {
    type: "Passif",
    name: "Bottes de Cowboy",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { speed: 0.1 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "cle_a_molette": {
    type: "Passif",
    name: "Clé à molette",
    sprite: "",
    bonus: "Cadence de tire",
    modifiers: { fireRate: 0.2 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 1
  },
  "reroll": {
    type: "Passif",
    name: "Reroll",
    sprite: "",
    price: 50,
    bonus: "Reroll",
    modifiers: { rerollToken: 1 },
    pool: "shop",
    target: "self",
    slot: "none",
    rarity: 1,
    extraInfo: "Achetable plusieurs fois (restock au près du marchant) mais augmente en prix a chaque achat. 50->55 ->60"
  },
  "module_explosif": {
    type: "Passif",
    name: "Module Explosif",
    sprite: "",
    bonus: "Explosion",
    modifiers: { explosionRadius: 3, explosionDamage: 7.5, explosionProc: 0.25 },
    pool: "chest",
    target: "on damage",
    slot: "arm",
    rarity: 3,
    extraInfo: "Explosion à l'impact (25% de chance)"
  },
  "defragmenteur": {
    type: "Passif",
    name: "Défragmenteur",
    sprite: "",
    bonus: "Tire",
    modifiers: { additionalProjectiles: 1, fireRate: -0.1 },
    pool: "chest",
    target: "self",
    slot: "arm",
    rarity: 3,
    extraInfo: "Ajoute un projectile (tir en cône)"
  },
  "sabots_d_acier": {
    type: "Actif",
    name: "Sabots d'Acier",
    sprite: "",
    modifiers: { aoeDamage: 5 },
    pool: "chest",
    cooldown: 10,
    target: "zone",
    slot: "leg",
    rarity: 3,
    extraInfo: "Fait une AoE tous les 10 pas"
  },
  "module_ignis": {
    type: "Passif",
    name: "Module Ignis",
    sprite: "",
    bonus: "Brûlure",
    modifiers: { burnDamage: 2, burnProc: 0.2 },
    pool: "chest",
    duration: 2,
    target: "on damage",
    slot: "arm",
    rarity: 3,
    effectType: "burn"
  },
  "module_glacies": {
    type: "Passif",
    name: "Module Glacies",
    sprite: "",
    bonus: "Ralentissement",
    modifiers: { slowEffect: 0.5, slowProc: 0.2 },
    pool: "chest",
    duration: 3,
    target: "on damage",
    slot: "arm",
    rarity: 3
  },
  "module_aero": {
    type: "Passif",
    name: "Module Aero",
    sprite: "",
    bonus: "Degats + KB",
    modifiers: { damage: 3, knockback: 1 },
    pool: "chest",
    cooldown: 3,
    target: "self",
    slot: "leg",
    rarity: 3
  },
  "equivalence": {
    type: "Passif",
    name: "Equivalence",
    sprite: "",
    bonus: "Emplacement",
    modifiers: {},
    pool: "shop",
    target: "self",
    slot: "none",
    rarity: 2,
    extraInfo: "Donne le choix de supprimer un emplacement de chassi (vide ou plein) contre un nouvel emplacement de chassis (vide)"
  },
  "huile": {
    type: "Passif",
    name: "Huile",
    sprite: "",
    bonus: "Cadence",
    modifiers: { fireRate: 0.5 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 2
  },
  "potion": {
    type: "Passif",
    name: "Potion",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damage: 0.5 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 2
  },
  "etoile": {
    type: "Passif",
    name: "Étoile",
    sprite: "",
    bonus: "Chance",
    modifiers: { luck: 0.5 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 2
  },
  "turbo": {
    type: "Passif",
    name: "Turbo",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { speed: 0.2 },
    pool: "chest",
    target: "self",
    slot: "leg",
    rarity: 2
  },
  "egalite": {
    type: "Actif",
    name: "Égalité",
    sprite: "assets/items/egalite.png",
    bonus: "Projectiles",
    modifiers: { orbitingProjectiles: 3 },
    pool: "fusion",
    duration: Infinity,
    cooldown: 5,
    target: "zone",
    slot: "none",
    rarity: 3,
    extraInfo: "Fusion de Pierre-Feuille-Ciseaux",
    description: "Bonus de projectiles en orbite"
  },
  "appropriation_mecanique": {
    type: "Passif",
    name: "Appropriation Mécanique",
    sprite: "",
    modifiers: { conversionChance: 0.1 },
    pool: "chest",
    procChance: 0.1,
    duration: 10,
    target: "on kill",
    slot: "head",
    rarity: 3,
    extraInfo: "Converti un ennemi catégorie <2 en allier "
  },
  "radioactivitee": {
    type: "Passif",
    name: "Radioactivitée",
    sprite: "",
    bonus: "Dégats",
    modifiers: { dotDamage: 0.2 },
    pool: "chest",
    duration: Infinity,
    target: "self",
    slot: "leg",
    rarity: 3,
    extraInfo: "Onde continu qui fait des dégats autour du joueur en continu 0,2 dégats/s"
  },
  "sacrifice": {
    type: "Passif",
    name: "Sacrifice",
    sprite: "",
    bonus: "Emplacement",
    modifiers: { damage: 1.5 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 3,
    extraInfo: "Supprime un emplacement de corp contre des dégats"
  },
  "mise_a_jour": {
    type: "Passif",
    name: "Mise à jour",
    sprite: "",
    bonus: "Refu de la mort",
    modifiers: { respawnCount: 1 },
    pool: "shop",
    target: "self",
    slot: "body",
    rarity: 3,
    extraInfo: "A la mort, fait respawn le joueur"
  },
  "virus": {
    type: "Actif",
    name: "Virus",
    sprite: "",
    bonus: "Berserk",
    modifiers: { damage: 0.5, speed: 0.2, fireRate: 0.2 },
    pool: "chest",
    duration: 8,
    cooldown: 30,
    target: "self",
    slot: "active",
    rarity: 3
  },
  "confiance": {
    type: "Passif",
    name: "Confiance",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damageMultiplier: 1.5, damageTakenMultiplier: 2 },
    pool: "chest",
    target: "self",
    slot: "body",
    rarity: 3
  },
  "ciblage": {
    type: "Passif",
    name: "Ciblage",
    sprite: "",
    bonus: "Projectile",
    modifiers: { homingProjectiles: true },
    pool: "chest",
    target: "other",
    slot: "head",
    rarity: 3
  },
  "supersonic": {
    type: "Passif",
    name: "Supersonic",
    sprite: "",
    bonus: "Dégats",
    modifiers: { areaDamage: 1 },
    pool: "chest",
    target: "zone",
    slot: "leg",
    rarity: 3
  },
  "immuable": {
    type: "Actif",
    name: "Immuable",
    sprite: "",
    bonus: "Hp",
    modifiers: { invulnerable: true },
    pool: "shop",
    duration: 7,
    cooldown: 20,
    target: "self",
    slot: "active",
    rarity: 3
  },
  "super_hot": {
    type: "Passif",
    name: "Super Hot",
    sprite: "",
    bonus: "Degat",
    modifiers: { contactDamage: 10, iframes: 0 },
    pool: "chest",
    cooldown: null,
    target: "self",
    slot: "body",
    rarity: 3
  },
  "tazer": {
    type: "Passif",
    name: "Tazer",
    sprite: "",
    bonus: "Degat",
    modifiers: { chainDamageCount: 5 },
    pool: "chest",
    target: "on damage",
    slot: "arm",
    rarity: 3,
    extraInfo: "fait des dégats a un ennemis le plus proche et... 5 ennemis de longueur"
  },
  "pression": {
    type: "Passif",
    name: "Pression",
    sprite: "",
    bonus: "Vitesse",
    modifiers: { enemySlowRadius: 5 },
    pool: "chest",
    target: "self",
    slot: "leg",
    rarity: 3
  },
  "reinitialisation": {
    type: "Actif",
    name: "Réinitialisation",
    sprite: "",
    bonus: "Replay",
    modifiers: { restartWithItems: true },
    pool: "shop",
    cooldown: Infinity,
    target: "self",
    slot: "active",
    rarity: 4,
    extraInfo: "Restart la game en gardant les items"
  },
  "coeur_de_centaure": {
    type: "Passif",
    name: "Coeur de Centaure",
    sprite: "assets/items/heart_centaure.png",
    bonus: "Régénération",
    modifiers: { healthRegen: 0.1 },
    pool: "chest",
    duration: Infinity,
    target: "self",
    slot: "body",
    rarity: 4
  },
  "surcharge_quantum": {
    type: "Passif",
    name: "Surcharge Quantum",
    sprite: "assets/items/quantum_force.png",
    bonus: "Dégats",
    modifiers: { damage: 1 },
    pool: "chest",
    target: "self",
    slot: "arm",
    rarity: 4
  },
  "processeur_fortune": {
    type: "Passif",
    name: "Processeur Fortune",
    sprite: "",
    bonus: "Chance",
    modifiers: { luck: 5 },
    pool: "chest",
    target: "self",
    slot: "head",
    rarity: 4
  },
  "bras_modulaire": {
    type: "Passif",
    name: "Bras Modulaire",
    sprite: "",
    bonus: "Emplacement",
    modifiers: { armSlots: 1 },
    pool: "chest",
    target: "self",
    slot: "none",
    rarity: 4
  },
  "solution_miracle": {
    type: "Passif",
    name: "Solution Miracle",
    sprite: "assets/items/solution_miracle.png",
    modifiers: { poisonToHeal: true },
    pool: "chest",
    target: "self",
    slot: "body",
    rarity: 4,
    extraInfo: "Transforme les dégâts de poisons en heal"
  },
  "vaillance": {
    type: "Passif",
    name: "Vaillance",
    sprite: "",
    modifiers: { itemEffectMultiplier: 2 },
    pool: "chest",
    procChance: 1,
    duration: Infinity,
    target: "self",
    slot: "head",
    rarity: 4,
    extraInfo: "double les effets chaque item qu'il récupère"
  },
  "richissime": {
    type: "Passif",
    name: "Richissime",
    sprite: "",
    price: 500,
    bonus: "Emplacement",
    modifiers: { bodySlots: 1 },
    pool: "shop",
    target: "self",
    slot: "none",
    rarity: 4,
    extraInfo: "Ajoute un emplacement de corp contre 500 coins"
  },
  "jambe_modulaire": {
    type: "Passif",
    name: "Jambe Modulaire",
    sprite: "",
    bonus: "Emplacement",
    modifiers: { legSlots: 1 },
    pool: "chest",
    target: "self",
    slot: "leg",
    rarity: 4
  },
  "corp_modulaire": {
    type: "Passif",
    name: "Corp Modulaire",
    sprite: "",
    bonus: "Emplacement",
    modifiers: { bodySlots: 1 },
    pool: "chest",
    target: "self",
    slot: "body",
    rarity: 4
  },
  "tete_modulaire": {
    type: "Passif",
    name: "Tête Modulaire",
    sprite: "",
    bonus: "Emplacement",
    modifiers: { headSlots: 1 },
    pool: "chest",
    target: "self",
    slot: "head",
    rarity: 4
  },
  "ace": {
    type: "Passif",
    name: "Ace",
    sprite: "",
    bonus: "Projectile",
    modifiers: { projectileMultiplier: 2 },
    pool: "chest",
    target: "other",
    slot: "arm",
    rarity: 4
  },
  "wind_up": {
    type: "Passif",
    name: "Wind Up",
    sprite: "",
    bonus: "Stats",
    modifiers: { preventStatDecrease: true },
    pool: "chest",
    target: "self",
    slot: "body",
    rarity: 4
  },
  "singularitee": {
    type: "Passif",
    name: "Singularitée",
    sprite: "",
    bonus: "Dégats",
    modifiers: { damageMultiplier: 2 },
    pool: "chest",
    target: "self",
    slot: "head",
    rarity: 4
  }
};